### ISSUE TITLE
Ext-address

### ISSUE THREAD

**Issue by hugoideler** [t4skforce/syncthing-relay-discovery#1]
Thanks for your docker image.

Would you please also consider making the following option configurable?
```
-ext-address string
      An optional address to advertise as being available on.
      Allows listening on an unprivileged port with port forwarding from e.g. 443, and be connected to on port 443.
```
See also: https://docs.syncthing.net/users/strelaysrv.html#running-on-port-443-as-an-unprivileged-user .

**Comment by t4skforce** [comment]
Hi @citral,

as this is a docker container does listening on 443 not work out of the box by launching the container with 
`docker run --name syncthing-relay -d -p 443:22067 -p 22026:22026 --restart=always t4skforce/syncthing-relay-discovery:latest`. With `-p 443:22067` the iptables mapping is done in docker and the discovery server is reachable via dockerhost:443. Or is there an issue with that I'm not aware of?

**Comment by hugoideler** [comment]
Hi @t4skforce,

I am doing NAT on both IP and port from another server. I found that I needed to place the external IP+port in that ext-address field to get it working, but I didn't (yet) debug why this is the case.

**Comment by t4skforce** [comment]
Hi @citral,

Just added new ENV variable to add addition parameters to the relaysrv start. RELAY_OPTS

so for your problem `-e RELAY_OPTS='--ext-address=":443"'` should work.

**Comment by hugoideler** [comment]
Hi @t4skforce, thanks for this fix! I just wanted to let you know that it works for me.

I had to use a slight variation (single dash and no extra quotes), i.e.: `-e RELAY_OPTS='-ext-address=:443'`.
